### ISSUE TITLE
After every try it says "/bin/bash: hashcat: command not found"

### ISSUE THREAD

**Issue by Shazgul** [1N53C/ColabCatWithHashIDandRules#1]
After every try it says "/bin/bash: hashcat: command not found", so i have to "Run ALL" again after every single cracking try!?

**Comment by 1N53C** [comment]
Never faced that problem myself. I added a line in the notepad to check, if hashcat was installed properly. 
Please check again, if the hashcat version shows up.
There should be no need to "run all" every time but if you haven't used it for a while, you have to run it all again because you are using a Google Server which will be reset from time to time.
